name: telegraf-slim
on:
  push:
    paths:
      - "main/telegraf-slim/**"
  workflow_dispatch:

jobs:
  telegraf-slim:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        alpine_version: [v3.23, edge]
        alpine_arch: [x86_64]

    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: all

      # - name: Cache Go Dependencies
      #   uses: actions/cache@v4
      #   with:
      #     path: |
      #       main/telegraf-slim/cache
      #     key: ${{ matrix.alpine_arch }}-slim-go-${{ hashFiles('**/go.sum') }}
      #     restore-keys: |
      #       ${{ matrix.alpine_arch }}-slim-go-

      # As of Jan 2026 the runner was failing due to running out of disk space, likely
      # from the Go dependency caching step, which wasn't working. If the problem comes
      # back, this scriptlet from https://www.geraldonit.com/ should clean up some
      # unnecessary things and gain back enough space to successfully build.
      # - name: Clean Up Disk Space
      #   if: runner.os == 'Linux'
      #   run: |
      #     # Space usage before cleanup
      #     df -h /
      
      #     # Remove unused tool caches (comment any required ones with #)
      #     sudo rm -rf /usr/lib/jvm
      #     sudo rm -rf /usr/local/.ghcup
      #     sudo rm -rf /usr/local/lib/android
      #     sudo rm -rf /usr/local/share/powershell
      #     sudo rm -rf /usr/share/dotnet
      #     sudo rm -rf /usr/share/swift
      #     sudo rm -rf "$AGENT_TOOLSDIRECTORY"
      
      #     # Verify gains
      #     df -h /

      - name: Install Deploy SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}

      - name: Synchronize Repository Packages
        run: rsync -avz "${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/srv/pkg/webroot/alpine/${{ matrix.alpine_version }}/main" ${HOME}/packages

      - name: Build Package
        run: docker run --rm -e "RSA_PRIVATE_KEY=${{ secrets.RSA_PRIVATE_KEY }}" -v "${{ github.workspace }}/main/telegraf-slim:/home/builder/main/package" -v "${HOME}/packages:/packages" asymworks/alpine-abuild-${{ matrix.alpine_arch }}:${{ matrix.alpine_version }}

      - name: Publish Repository Packages
        run: rsync -avz ~/packages/main/${{ matrix.alpine_arch }}/./ "${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/srv/pkg/webroot/alpine/${{ matrix.alpine_version }}/main/${{ matrix.alpine_arch }}/"

  telegraf-slim-arm:
    runs-on: ubuntu-24.04-arm
    strategy:
      matrix:
        alpine_version: [v3.23, edge]
        alpine_arch: [aarch64]

    steps:
      - uses: actions/checkout@v2

      # - name: Cache Go Dependencies
      #   uses: actions/cache@v4
      #   with:
      #     path: |
      #       main/telegraf-slim/cache
      #     key: ${{ matrix.alpine_arch }}-slim-go-${{ hashFiles('**/go.sum') }}
      #     restore-keys: |
      #       ${{ matrix.alpine_arch }}-slim-go-

      # - name: Clean Up Disk Space
      #   if: runner.os == 'Linux'
      #   run: |
      #     # Space usage before cleanup
      #     df -h /
      
      #     # Remove unused tool caches (comment any required ones with #)
      #     sudo rm -rf /usr/lib/jvm
      #     sudo rm -rf /usr/local/.ghcup
      #     sudo rm -rf /usr/local/lib/android
      #     sudo rm -rf /usr/local/share/powershell
      #     sudo rm -rf /usr/share/dotnet
      #     sudo rm -rf /usr/share/swift
      #     sudo rm -rf "$AGENT_TOOLSDIRECTORY"
      
      #     # Verify gains
      #     df -h /

      - name: Install Deploy SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}

      - name: Synchronize Repository Packages
        run: rsync -avz "${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/srv/pkg/webroot/alpine/${{ matrix.alpine_version }}/main" ${HOME}/packages

      - name: Build Package
        run: docker run --rm -e "RSA_PRIVATE_KEY=${{ secrets.RSA_PRIVATE_KEY }}" -v "${{ github.workspace }}/main/telegraf-slim:/home/builder/main/package" -v "${HOME}/packages:/packages" asymworks/alpine-abuild-${{ matrix.alpine_arch }}:${{ matrix.alpine_version }}

      - name: Publish Repository Packages
        run: rsync -avz ~/packages/main/${{ matrix.alpine_arch }}/./ "${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/srv/pkg/webroot/alpine/${{ matrix.alpine_version }}/main/${{ matrix.alpine_arch }}/"

